name: RockPaperScissors
version: ${project.version}
main: dev.lightdream.rps.Main
authors: [ L1ghtDream ]
website: https://lightdream.dev
softdepend:
  - LightDreamAPI
commands:
  rps:
    description: NA
  ld-api:
    description: NA